openapi: '3.0.0'
info:
  version: 0.0.1
  title: Music shorts
  description: Music shorts app & admin api docs
  license:
    name: GLP 3.0
servers:
  - url: https://us-central1-music-shorts.cloudfunctions.net/api
paths:
  /auth/oauthurl/spotify: 
    $ref: './auth.yaml#/~1auth~1oauthurl~1spotify'
  /auth/token/swap:
    $ref: './auth.yaml#/~1auth~1token~1swap'
  /auth/token/refresh:
    $ref: './auth.yaml#/~1auth~1token~1refresh'
  /albums/{id}:
    $ref: './albums.yaml#/~1albums~1{id}'
  /me:
    $ref: './me.yaml#/~1me'
  /me/playlist/tracks:
    $ref: './me.yaml#/~1me~1playlist~1tracks'
  /me/playlist/tracks/{id}:
    $ref: './me.yaml#/~1me~1playlist~1tracks~1{id}'
  /search:
    $ref: './search.yaml#/~1search'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  responses:
    successResponse:
      description: successful request
      content:
        application/json:
          schema:
            type: object
